/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VoteChain } from './VoteChain.js';
export * as factories from './factories/index.js';
export { VoteChain__factory } from './factories/VoteChain__factory.js';