/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace VoteChain {
      
    export type CandidateStruct = {id: BigNumberish, name: string, party: string, voteCount: BigNumberish}

    export type CandidateStructOutput = [id: bigint, name: string, party: string, voteCount: bigint] & {id: bigint, name: string, party: string, voteCount: bigint }
  
    }

  export interface VoteChainInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "admin" | "candidates" | "castVote" | "createElection" | "election" | "endElection" | "getCandidate" | "getCandidateCount" | "getCandidates" | "getElectionStatus" | "getWinner" | "hasVoted" | "isElectionActive" | "isWhitelisted" | "totalVotes" | "votedFor" | "whitelistVoter" | "whitelistVotersBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateAdded" | "ElectionCreated" | "ElectionEnded" | "VoteCast" | "VoterWhitelisted"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [string, string]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'castVote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createElection', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'election', values?: undefined): string;
encodeFunctionData(functionFragment: 'endElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidateCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getElectionStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWinner', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isElectionActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'isWhitelisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalVotes', values?: undefined): string;
encodeFunctionData(functionFragment: 'votedFor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'whitelistVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'whitelistVotersBatch', values: [AddressLike[]]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'castVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'election', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElectionStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isElectionActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votedFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistVotersBatch', data: BytesLike): Result;
  }

  
    export namespace CandidateAddedEvent {
      export type InputTuple = [candidateId: BigNumberish, name: string, party: string];
      export type OutputTuple = [candidateId: bigint, name: string, party: string];
      export interface OutputObject {candidateId: bigint, name: string, party: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [title: string, startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [title: string, startTime: bigint, endTime: bigint];
      export interface OutputObject {title: string, startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionEndedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [voter: AddressLike, candidateId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [voter: string, candidateId: bigint, timestamp: bigint];
      export interface OutputObject {voter: string, candidateId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterWhitelistedEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VoteChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): VoteChain;
    waitForDeployment(): Promise<this>;

    interface: VoteChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_name: string, _party: string, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint] & {id: bigint, name: string, party: string, voteCount: bigint }],
      'view'
    >
    

    
    castVote: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createElection: TypedContractMethod<
      [_title: string, _description: string, _startTime: BigNumberish, _endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    election: TypedContractMethod<
      [],
      [[string, string, bigint, bigint, boolean] & {title: string, description: string, startTime: bigint, endTime: bigint, exists: boolean }],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getCandidate: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [VoteChain.CandidateStructOutput],
      'view'
    >
    

    
    getCandidateCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCandidates: TypedContractMethod<
      [],
      [VoteChain.CandidateStructOutput[]],
      'view'
    >
    

    
    getElectionStatus: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getWinner: TypedContractMethod<
      [],
      [VoteChain.CandidateStructOutput],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isElectionActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isWhitelisted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    totalVotes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    votedFor: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    whitelistVoter: TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    whitelistVotersBatch: TypedContractMethod<
      [_voters: AddressLike[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, _party: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint] & {id: bigint, name: string, party: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'castVote'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [_title: string, _description: string, _startTime: BigNumberish, _endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'election'): TypedContractMethod<
      [],
      [[string, string, bigint, bigint, boolean] & {title: string, description: string, startTime: bigint, endTime: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [VoteChain.CandidateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidateCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidates'): TypedContractMethod<
      [],
      [VoteChain.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getElectionStatus'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getWinner'): TypedContractMethod<
      [],
      [VoteChain.CandidateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isElectionActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isWhitelisted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votedFor'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistVoter'): TypedContractMethod<
      [_voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'whitelistVotersBatch'): TypedContractMethod<
      [_voters: AddressLike[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CandidateAdded'): TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'ElectionEnded'): TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VoterWhitelisted'): TypedContractEvent<VoterWhitelistedEvent.InputTuple, VoterWhitelistedEvent.OutputTuple, VoterWhitelistedEvent.OutputObject>;

    filters: {
      
      'CandidateAdded(uint256,string,string)': TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
      CandidateAdded: TypedContractEvent<CandidateAddedEvent.InputTuple, CandidateAddedEvent.OutputTuple, CandidateAddedEvent.OutputObject>;
    

      'ElectionCreated(string,uint256,uint256)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'ElectionEnded(uint256)': TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
      ElectionEnded: TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
    

      'VoteCast(address,uint256,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VoterWhitelisted(address)': TypedContractEvent<VoterWhitelistedEvent.InputTuple, VoterWhitelistedEvent.OutputTuple, VoterWhitelistedEvent.OutputObject>;
      VoterWhitelisted: TypedContractEvent<VoterWhitelistedEvent.InputTuple, VoterWhitelistedEvent.OutputTuple, VoterWhitelistedEvent.OutputObject>;
    
    };
  }